### ISSUE TITLE
Invalid aspectjweaver path in case of spaces in path

### ISSUE THREAD

**Issue by baev** [allure-framework/allure-gradle#15]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### Please tell us about your environment:

| Allure version | any |
| --- | --- |
| Test framework | any |
| Allure adaptor | any |
| Generate report using | any |

#### Other information 

in line https://github.com/allure-framework/allure-gradle/blob/master/src/main/groovy/io/qameta/allure/gradle/AllurePlugin.groovy#L131 path should be escaped:

`"-javaagent:\"${aspectjConfiguration.singleFile}\""` 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by eroshenkoam** [comment]
It doesn't work like that: https://github.com/allure-framework/allure-gradle/pull/18
