### ISSUE TITLE
jUnit 5 support

### ISSUE THREAD

**Issue by eroshenkoam** [allure-framework/allure-gradle#17]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Allure Gradle doesn't support junit 5 integration

#### What is the expected behavior?

useJunit5 {
}

#### Please tell us about your environment:

| Allure version | any |
| --- | --- |
| Test framework | junit@5.x |
| Allure adaptor | any |
| Generate report using | allure-gradle@2.3 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by sskorol** [comment]
See original SO question: https://stackoverflow.com/questions/45686139/test-reporting-with-allure-in-junit-5
