### ISSUE TITLE
Consequent builds are failing when allure-gradle is used with Gradle 5.0 and Kotlin DSL

### ISSUE THREAD

**Issue by dkorobtsov** [allure-framework/allure-gradle#36]
#### I'm submitting a ... 
  - [X ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Consequent builds are failing when allure-gradle is used with Gradle 5.0 and Kotlin DSL

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Clone https://github.com/dkorobtsov/allure-kotlin
2. Import repository as gradle project
3. Open gradle console
4. in 'verification' tab execute 'test' task
5. in 'other' tab execute task 'allureServe'
6. Check that report is generated as expected
7. repeat step 4, run 'test' again (without cleaning project)
8. Expected result: 

#### What is the expected behavior?
test should run without cleaning project

#### What is the motivation / use case for changing the behavior?
Library is useless with Gradle 5.0 and Kotlin DSL.

#### Please tell us about your environment:
Check demo project dependencies.
NB. issue reproduces on MacOS. Haven't tried on other systems.

**Comment by vlsi** [comment]
This PR adds Gradle 5.0...7.0 with a streamlined DSL: https://github.com/allure-framework/allure-gradle/pull/61
See the new DSL at https://github.com/vlsi/allure-gradle/tree/facelift#basic-usage

Please feel free to try it and provide feedback

**Comment by vlsi** [comment]
Resolved in #61
