### ISSUE TITLE
allure 2.8.0 fot gradle plugin

### ISSUE THREAD

**Issue by Shaihuludus** [allure-framework/allure-gradle#38]
Hello,

We are using Allure as report engine in our automated test framework. The last available Allure version for gradle plugin and junit5 is 2.7.0. Is there going to be release for 2.8.0?

**Comment by Brian-Dawson-Nerdery** [comment]
I believe you can change the report download URL to their new report repo and get the new versions that way. 

Try adding:
```gradle
allure {
    version = '2.8.1'
    downloadLink = 'http://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.8.1/allure-commandline-2.8.1.zip'
}
```

**Comment by abarsov** [comment]
please, accept both old and new versions without making it necessary to define `downloadLink` explicitly.
