### ISSUE TITLE
Plugin not work in gradle 5.1+

### ISSUE THREAD

**Issue by admizh** [allure-framework/allure-gradle#44]
https://github.com/allure-framework/allure-gradle/blob/3ed5c24dc6959dde5326cdb8fe9b3959195334bd/src/main/groovy/io/qameta/allure/gradle/task/AllureReport.groovy#L8

for Gradle 5.0 the internal class org.gradle.api.internal.ClosureBackedAction has been moved to org.gradle.util.ClosureBackedAction: https://github.com/gradle/gradle/issues/8026

**Comment by vlsi** [comment]
This PR adds Gradle 5.0...7.0 compatibility: https://github.com/allure-framework/allure-gradle/pull/61

Please feel free to try it and provide feedback

**Comment by vlsi** [comment]
Fixed in #61
