### ISSUE TITLE
Add capability to pass Host/Port config when running  gradle task "allureServe"

### ISSUE THREAD

**Issue by RamiaSaidawi** [allure-framework/allure-gradle#57]
[//]: # (
When running gradle task "allureServe" i want to be able to specify the host/port used to serve the reports on 
)

#### I'm submitting a ... 
  - [ ] bug report
  - [Yes ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When running "gradle allureServe" i cannot specify what host/port  i want the reports to be served on.
running Allure command line "allure serve" give the ability to specify host/port if needed 
$> allure serve -h 127.0.0.1 -p 3030  

#### What is the expected behavior?
i expect for gradle task "allureServe" to have same flexibility as "serve" command line  
so i can setup host/port as part of the configuration

#### What is the motivation / use case for changing the behavior?
for data privacy we cannot use the tool if it upload results to hosts outside our domain 

#### Please tell us about your environment:

| Allure version | 2.13.6 |
| --- | --- |
| Test framework | junit@4.13.1 |
| Allure adaptor | allure-junit4@2.13.6 |
| Generate report using | allure-gradle@2.18 |

#### Other information 

this is what i think can be a fast fix, based on my limited knowledge of the code 
 
```
_//## **in class AllureExtension :**_ 
_//## add properties so we can set as part of allure configuration_
String host
Int port
 

_//##  **in  class AllureServe extends DefaultTask**_
_//## add extra parameters_
@Input
    String host
@Input
    int port

void configureDefaults() {
        AllureExtension allureExtension = project.extensions.findByType(AllureExtension)
        if (Objects.nonNull(extensions)) {
            resultsDirs.add(allureExtension.resultsDir)
            version = allureExtension.version
            _//## read the host/port values_ 
            port = allureExtension.port
            host = allureExtension.host
        }
    }
)

_//## add  " -p port -h host"  to  "SERVE_COMMAND"_ 
_//## make sure port/host stay optional so projects dont care to change them still work_
project.exec {
            commandLine("$allureExecutable")
            args(SERVE_COMMAND)
            resultsDirs.each {
                copyCategoriesInfo(it, project)
                copyExecutorInfo(it, project)
                args("$it.absolutePath")
            }
        }

```

**Comment by vlsi** [comment]
This PR adds `--host` and `--port` parameters to `allureServe` and `allureAggregateServe` tasks: https://github.com/allure-framework/allure-gradle/pull/61

Please feel free to try it and provide feedback

**Comment by vlsi** [comment]
Which plugin version do you use?

**Comment by pandoras-toolbox** [comment]
I upgraded the Allure plugin to 2.9.4, the option --host now can be used, thank you. But in IntelliJ it does not display anymore the Gradle tasks "allureReport" and "allureServe". If I want them back I have to add the tasks myself in our project I guess.

**Comment by vlsi** [comment]
Please check "verification" task group, the tasks should be there.

**Comment by RamiaSaidawi** [comment]
I was able to run with local host 
created this task
task('localAllureServe', type: Exec, group: 'verification') {
    executable './gradlew'
    args 'allureServe', '--host', 'localhost'
}

thank you
