### ISSUE TITLE
JCenter sundown

### ISSUE THREAD

**Issue by realdadfish** [allure-framework/allure-gradle#63]
While now put on "read-only for the community", Bintray's jcenter is no longer a viable option to publish / host artifacts. (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

It would be great if the project could therefor offer an alternative hosting, e.g. mavenCentral.

Thanks!

**Comment by vlsi** [comment]
AFAIK the project no longer uses Bintray / JCenter, and the plugin is available via Gradle Plugin Portal: https://plugins.gradle.org/search?term=io.qameta.allure

**Comment by realdadfish** [comment]
Ok, apparently this is no longer an issue then. Thanks for the heads-up!
