### ISSUE TITLE
Instead of the "allureServe" gradle task, the "test" task is executed

### ISSUE THREAD

**Issue by avadanilov** [allure-framework/allure-gradle#73]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report

#### What is the current behavior?

Instead of the "allureServe" gradle task, the "test" task is executed

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Updated gradle plugin from version 2.8.1 to version 2.9.3
1. Opening the gradle panel in Idea
2. Run the "allureServe" task
3. The build of the project started, incl. "test" task
(screen in atach)

#### What is the expected behavior?
The server will start and the browser tab will open with the Allure report

#### Please tell us about your environment:

| Allure version | 2.9.3 |
| --- | --- |
| Test framework | JUnit5 |

#### Other information 
![photo_2021-09-29_10-13-30](https://user-images.githubusercontent.com/66197323/135220626-e15aabf4-f109-4e75-ba51-61e8c6889d33.jpg)

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by vlsi** [comment]
@avadanilov , please provide the reproducer.

```kotlin
plugins {
    id("java-library")
    id("io.qameta.allure") version "2.9.3"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.8.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}

allure {
    report {
        version.set("2.14.0")
    }
    adapter {
        allureJavaVersion.set("2.14.0")
    }
}
```

<img width="946" alt="allureServe" src="https://user-images.githubusercontent.com/213894/135237758-fa7c7fbe-8324-4373-a035-da08352688b0.png">
