### ISSUE TITLE
Able use custom java sdk 

### ISSUE THREAD

**Issue by sshuvalov** [allure-framework/allure-gradle#81]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] feature request

#### What is the current behavior?

Executing `allureServe` task throws `ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.`

#### What is the expected behavior?

I want to be able to set custom java sdk as gradle task option like this:

```gradle
allure {
    javaHomePath = '/my/custom/sdk/path'
}
```

**Comment by vlsi** [comment]
We'd probably want using Gradle Java Toolchains: https://docs.gradle.org/current/userguide/toolchains.html#sec:plugins

**Comment by vlsi** [comment]
Ah, the plugin calls Allure binary as a regular executable, so we probably want to expose `environment variables` for launching the executable.
