### ISSUE TITLE
Allure commandline is downloaded into `build/allure` folder, but previously it was donwloaded into `.allure` folder in the project root

### ISSUE THREAD

**Issue by rromanik** [allure-framework/allure-gradle#83]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When using the current version of allure gradle plugin `2.9.6`, the `downloadAllure` task downloads the allure commandline into the folder `/build/allure`.
When using a previous version, e.g. `2.8.1`, it was downloaded into `.allure` folder directly under the project root.
Thus, previously, when the `clean` task deleted the `build` folder, there were no need to download Allure commandline again.
Now, it must be downloaded each time after `clean` task.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Just run `downloadAllure` task and find that allure is downloaded into `build/allure` folder.

#### What is the expected behavior?
Allure is downloaded into `.allure` folder under the project root.

#### What is the motivation / use case for changing the behavior?
Previously (e.g. in version `2.8.1`) the task `downloadAllure` would be considered up-to-date after executing `./gradlew clean`, and no redundant allure download would be performed.
Now, allure needs to be downloaded again after `./gradlew clean`.

#### Please tell us about your environment:

| Allure Gradle plugin version | 2.9.6 |
| --- | --- |
| Gradle (wrapper) | 7.3 |
| Allure version | 2.16.1 |
| Test framework | testng@7.4.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
I think no other information is needed.
However, maybe downloading into `/build/allure` folder is a new expected behavior?

**Comment by vlsi** [comment]
`downloadAllure` uses Gradle's default dependency resolution engine, so Allure is cached in `$HOME/.gradle/...`, and it is NOT downloaded again even if you run `./gradlew clean`.
