### ISSUE TITLE
Issue integrating allure-plugin into build-conventions

### ISSUE THREAD

**Issue by realdadfish** [allure-framework/allure-gradle#84]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

If `io.qameta.allure` is used in a kotlin-dsl enabled `build-convention` plugin, the Kotlin DSL code generator cannot find the type like `io.qameta.allure.gradle.adapter.AllureAdapterExtension` (and neither are those available during script editing) and as such the plugin cannot be configured. The `:build-conventions:dependencies` output however properly lists the main plugin dependencies (namely *-report and *-adapter) properly.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

/build-conventions/build.gradle.kts:
```
plugins {
    `kotlin-dsl`
}

dependencies {
    implementation("io.qameta.allure.gradle.allure:allure-plugin:2.9.6")
}
```
/build-conventions/src/main/kotlin/my-shared-conventions.gradle.kts:
```
plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm")
    id("io.qameta.allure")
}

val allureVersion = "2.17.2"
allure.version.set(allureVersion)
allure.adapter.allureJavaVersion.set(allureVersion)
allure.adapter.aspectjWeaver.set(true)
```

Error:

```
e: /path/to/build-conventions/src/main/kotlin/my-shared-conventions.gradle.kts: (26, 8): Function invocation 'version(...)' expected
e: /path/to/build-conventions/src/main/kotlin/my-shared-conventions.gradle.kts: (8, 8): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public infix fun PluginDependencySpec.version(version: String?): PluginDependencySpec defined in org.gradle.kotlin.dsl
public infix fun PluginDependencySpec.version(version: Provider<String>): PluginDependencySpec defined in org.gradle.kotlin.dsl
e: /path/to/build-conventions/src/main/kotlin/my-shared-conventions.gradle.kts: (9, 8): Unresolved reference: adapter
```

#### What is the expected behavior?

Plugin application should work. My current workaround ist to apply the base and adapter / reporting plugins manually, like so:

```
dependencies {
    val allurePlugin = "2.9.6"
    implementation("io.qameta.allure.gradle.base:allure-base-plugin:$allurePlugin")
    implementation("io.qameta.allure.gradle.adapter:allure-adapter-plugin:$allurePlugin")
    implementation("io.qameta.allure.gradle.report:allure-report-plugin:$allurePlugin")
}
...
plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm")
    id("io.qameta.allure-base")
    id("io.qameta.allure-adapter")
    id("io.qameta.allure-report")
}
```

#### Please tell us about your environment:

| Allure Gradle version | 2.9.6 |

**Comment by vlsi** [comment]
@realdadfish , would you please double-check if just adding `allure-base-plugin`,  `allure-adapter-plugin`, `allure-report-plugin` (to `/build-conventions/build.gradle.kts`) and applying only `io.qameta.allure` in `my-shared-conventions.gradle.kts` would work?
